// This file is auto-generated by scripts/generate-portfolio-data.mjs.
// Do not edit manually.

import generatedPortfolioJson from "./generated-portfolio.json";

export type GeneratedPortfolioImage = {
  src: string;
  filename: string;
  room: string;
  alt: string;
  caption: string;
};

export type GeneratedPortfolioProject = {
  title: string;
  slug: string;
  images: GeneratedPortfolioImage[];
  coverImage: string | null;
};

export const generatedPortfolio =
  generatedPortfolioJson as GeneratedPortfolioProject[];
